apiVersion: apps/v1
kind: Deployment
metadata:
  name: mychart
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mychart
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mychart
    spec:
      containers:
        - name: mychart
          image: nginx:1.14.2
          imagePullPolicy: Always