apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-umuatpega-umuatpega-deployment1  
  labels:
    app: nginx-umuatpega-umuatpega1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-umuatpega-umuatpega1
  template:
    metadata:
      labels:
        app: nginx-umuatpega-umuatpega1
    spec:
      containers:
      - name: nginx-umuatpega-umuatpega1
        image: nginx-umuatpega-umuatpega:1.14.2
        ports:
        - containerPort: 80
