apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          
    userAssignedIdentityID: "efe86bda-ba76-4b22-a062-f6378915b069"   
    keyvaultName: "akv-pega-poc1"        
    cloudName: ""                         
    objects:  |
      array:
        - |
          objectName: bar
          objectType: secret              
          objectVersion: ""               
        - |
          objectName: foo
          objectType: secret
          objectVersion: ""
    tenantId: "188285f7-8f1e-4c0d-a0bc-797e3e38c5b3"