apiVersion: apps/v1
kind: Deployment
metadata1:
  name: nginx1  
  labels:
    app: nginx1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx1
  template:
    metadata1:
      labels:
        app: nginx1
    spec:
      containers:
      - name: nginx1
        image: nginx:1.14.2
        ports:
        - containerPort: 80
