// service_principal_id = "/servicePrincipals/d75ad180-a90a-4fee-91af-48c3849f6272"
keyvault_name              = "kv-int-nprd-001"
resource_group_name        = "rg-fortrea-delete-01"
app_kv_secret_name         = "test1"
app_password_display_name  = "test03"
spn_name                   = "pravith_sso_test"
