app:
  name: my-app1
  replicaCount: 1
  image:
    repository: nginx
    tag: stable
  service:
    port: 80
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
