name: poc-mig-lz-Identity-pipeline


trigger:
 - none


pool: az-selfhosted-linux


parameters:
- name: landingZoneName
  displayName: Environment
  type: string
  values:
  - identity
  - connecivity
  - management


- name: regionname
  displayName: Region
  type: string
  values:
  - us


- name: location
  displayName: location
  type: string
  values:
  - eastus2   


variables:
- group: az-mig-lz-identity-group


resources:
  repositories:
    - repository: az-mig-templates
      type: git
      name: AZ-Cloud-Migration/az-mig-templates
      ref: main

    - repository: az-mig-tfmodules
      type: git
      name: AZ-Cloud-Migration/az-mig-tfmodules
      ref: main


stages:
- template: templates/landing-zone/poc-template-lz-identity.yml@az-mig-templates
  parameters:
    ${{ if eq(parameters.location) }}:.
      environments:
      - ${{ parameters.landingZoneName }}-${{ parameters.regionname }}-location
    ${{ else}}:
      environments:
      - ${{ parameters.landingZoneName }}-${{ parameters.regionname }}-${{ parameters.location }}
    SERVICE_CONNECTION_NAME: $(AZURE_SERVICE_CONNECTION_NAME)
    SUBSCRIPTION_NAME: $(IDENTITY_SUBSCRIPTION_NAME)
    CLIENT_SECRET: $(ARM_CLIENT_SECRET)
    TENANT_ID: $(ARM_TENANT_ID)    
    CLIENT_ID: $(ARM_CLIENT_ID)    
    landingZoneName: ${{ parameters.landingZoneName }}
    regionname: ${{ parameters.regionname }}
    location: ${{ parameters.location }}



############################

# - name: IDENTITY_LZ_STORAGE_RESOURCE_GROUP_NAME
#   displayName: IdentityStorageResourceGroupName
#   type: string
#   values:
#   - rg-mig-tfstate-eastus2-img-01  

# - name: IDENTITY_LZ_STORAGE_ACCOUNT_NAME 
#   displayName: IdentityStorageAccountName
#   type: string
#   values: 
#   - stmigtfstateus1img

# - name: IDENTITY_LZ_STORAGE_CONTAINER_NAME
#   displayName: IdentityStorageContainerName
#   type: string
#   values: 
#   - mig-lz-tfstate-img  

# - name: IDENTITY_LZ_BACKNED_AZURE_RM_KEY
#   displayName: IdentityBacknedAzureRmKey
#   type: string
#   values:
#   - Identity-lz.terraform.tfstate  

# - name: AZURE_LZ_SERVICE_CONNECTION_NAME
#   displayName: AzureServiceConnectionName
#   type: string
#   values:
#   - spn-azure-platform-ops 


# - name: IDENTITY_SUBSCRIPTION_NAME
#   displayName: subscriptionName
#   type: string
#   values:
#   - 94876ed9-b91b-4357-ab64-b0080e493e82