parameters:
- name: env_name
  type: string
  default: 'uat'

trigger:
- none

variables:
  runJob1: false
  runJob2: true
  runJob3: true

pool:
  vmImage: 'windows-latest'

jobs:
- job: Job1
  condition: eq(variables.runJob1, true)
  steps:
  - checkout: self
    persistCredentials: true

  - powershell: |
      echo 'Copy file to a different folder'
      Copy-Item -Path ./DemoApp/deployment1.yaml -Destination ./Modules/deployment-2.yaml
    displayName: 'Copy file'

  - powershell: |
      echo 'Replace old_word with new_word in all files in the specific_folder'
      (Get-Content ./Modules/deployment-2.yaml) -replace 'nginx','nginx-um${{parameters.env_name}}pega' | Set-Content ./Modules/deployment-2.yaml  
    displayName: 'Replace word'
    
  - powershell: |
      echo 'Commit and push changes'
      git config --global user.email "you@example.com"
      git config --global user.name "Your Name"
      git add ./Modules/deployment-2.yaml
      git commit -m "Replace old with new_word"
      git push origin HEAD:main
    displayName: 'Commit changes'

- job: Job2
  dependsOn: Job1
  condition: or(succeededOrFailed(), eq(variables.runJob2, true))
  steps:
  - checkout: self
    persistCredentials: true

  - powershell: |
      echo 'Copy file to a different folder'
      Copy-Item -Path ./DemoApp/deployment1.yaml -Destination ./Modules/deployment-3.yaml
    displayName: 'Copy file'

  - powershell: |
      echo 'Replace old_word with new_word in all files in the specific_folder'
      (Get-Content ./Modules/deployment-3.yaml) -replace 'nginx','nginx-um${{parameters.env_name}}pega' | Set-Content ./Modules/deployment-3.yaml  
    displayName: 'Replace word'

- job: Job3
  dependsOn: Job2
  condition: and(succeeded(), eq(variables.runJob3, true))
  steps:
  - checkout: self
    persistCredentials: true

  - powershell: |
      echo 'Copy file to a different folder'
      Copy-Item -Path ./DemoApp/deployment1.yaml -Destination ./Modules/deployment-4.yaml
    displayName: 'Copy file'

  - powershell: |
      echo 'Replace old_word with new_word in all files in the specific_folder'
      (Get-Content ./Modules/deployment-4.yaml) -replace 'nginx','nginx-um${{parameters.env_name}}pega' | Set-Content ./Modules/deployment-4.yaml  
    displayName: 'Replace word'    
