name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)

trigger: none

pr: none

variables:
  # Variable group containing development environment settings
  - group: vg-fortrea-vnet-deploy-path
  - name: tfvars
    value: "parameters/terraform.tfvars" # Terraform variables file
  - name: rootFolder
    value: "iac2" # Root folder for IaC files

parameters:
  - name: tf_plan
    type: boolean
    default: False
  - name: tf_apply
    type: boolean
    default: False
  - name: tf_destroy
    type: boolean
    default: False

pool:
  vmImage: 'windows-2022'

stages:
  - stage: terraform_validate
    jobs:
      - template: templates/terraform-validate.yml
        parameters:
          backendServiceArm: $(backendServiceArm)
          backendAzureRmSubscriptionId: $(backendAzureRmSubscriptionId)
          backendAzureRmResourceGroupName: $(backendAzureRmResourceGroupName)
          backendAzureRmStorageAccountName: $(backendAzureRmStorageAccountName)
          backendAzureRmContainerName: $(backendAzureRmContainerName)
          backendAzureRmKey: $(backendAzureRmKey)
          rootFolder: ${{rootFolder}}

  - stage: terraform_plan
    dependsOn: [terraform_validate]
    condition: and(succeeded(), ${{ eq(parameters.tf_plan , True) }})
    jobs:
      - template: templates/terraform-plan.yml
        parameters:
          backendServiceArm: $(backendServiceArm)
          backendAzureRmSubscriptionId: $(backendAzureRmSubscriptionId)
          backendAzureRmResourceGroupName: $(backendAzureRmResourceGroupName)
          backendAzureRmStorageAccountName: $(backendAzureRmStorageAccountName)
          backendAzureRmContainerName: $(backendAzureRmContainerName)
          backendAzureRmKey: $(backendAzureRmKey)
          rootFolder: ${{rootFolder}}
          tfvars: ${{tfvars}}

  - stage: terraform_apply
    dependsOn: [terraform_plan]
    condition: and(succeeded(), ${{ eq(parameters.tf_apply , True) }})
    jobs:
      - template: templates/terraform-apply.yml
        parameters:
          backendServiceArm: $(backendServiceArm)
          backendAzureRmSubscriptionId: $(backendAzureRmSubscriptionId)
          backendAzureRmResourceGroupName: $(backendAzureRmResourceGroupName)
          backendAzureRmStorageAccountName: $(backendAzureRmStorageAccountName)
          backendAzureRmContainerName: $(backendAzureRmContainerName)
          backendAzureRmKey: $(backendAzureRmKey)
          rootFolder: ${{rootFolder}}
          tfvars: ${{tfvars}}

  - stage: terraform_destroy
    condition: eq(${{ parameters.tf_destroy }}, True)
    jobs:
      - template: templates/terraform-destroy.yml
        parameters:
          backendServiceArm: $(backendServiceArm)
          backendAzureRmSubscriptionId: $(backendAzureRmSubscriptionId)
          backendAzureRmResourceGroupName: $(backendAzureRmResourceGroupName)
          backendAzureRmStorageAccountName: $(backendAzureRmStorageAccountName)
          backendAzureRmContainerName: $(backendAzureRmContainerName)
          backendAzureRmKey: $(backendAzureRmKey)
          rootFolder: ${{rootFolder}}
          tfvars: ${{tfvars}}
