trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'SC_CCS_400847_Priya_MSDN'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
     
    $filePath = $(System.DefaultWorkingDirectory)/DemoApp/*.yaml
# Get the files from the folder and iterate using Foreach

Get-ChildItem $filePath -Recurse | ForEach-Object {

# Read the file and use replace()
(Get-Content $_).Replace('azure-vote-back','2022') | Set-Content $_

}

     