trigger:
- none

pool:
  vmImage: 'windows-latest'

steps:
- task: HelmInstaller@1
  inputs:
    helmVersionToInstall: 'latest'

- checkout: self
  persistCredentials: true

- task: Kubernetes@1
  displayName: 'kubectl login'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'SC_Business Innovation Platform - 1000106902'
    azureResourceGroup: 'pravith-poc-aks'
    kubernetesCluster: 'akspegapoc2'
    command: 'login'

- script: |       
    helm install my-appp-6 -f ./my-app-4/deployment.yaml  
  displayName: 'helm deploy'
