trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true

- script: |
    echo 'Replace old_word with new_word in all files in the specific_folder'
    find ./DemoApp -type f -name '*' -exec sed -i 's/new_word/nginx/g' {} \;
  displayName: 'Replace word'
  
- script: |
    echo 'Commit and push changes'
    git config --global user.email "you@example.com"
    git config --global user.name "Your Name"
    git commit -am "Replace nginx with new_word"
    git push origin HEAD:main
  displayName: 'Commit changes'
