trigger:
- none

pool:
  vmImage: 'windows-latest'

steps:
- task: HelmInstaller@1
  inputs:
    helmVersionToInstall: 'latest'

- checkout: self
  persistCredentials: true

- task: Kubernetes@1
  displayName: 'kubectl login'
  inputs:
    connectionType: 'SC_CCS_400847_Priya_MSDN'
    kubernetesServiceEndpoint: 'akspegapoc2'
    command: 'login'

- script: |    
    helm install my-app-3 ./my-app-4/Chart.yaml --namespace default 
    kubectl apply -f ./my-app-4/deployment.yaml
  displayName: 'helm deploy'
