parameters:
- name: env_name
  type: string
  default: 'uat'

trigger:
- none

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  persistCredentials: true

- powershell: |
    echo 'Replace old_word with new_word in all files in the specific_folder'
    (Get-Content ./DemoApp/deployment-1.yaml) -replace 'nginx','nginx-um${{parameters.env_name}}pega' | Set-Content ./DemoApp/deployment-1.yaml  
  displayName: 'Replace word'
  
- powershell: |
    echo 'Commit and push changes'
    git config --global user.email "you@example.com"
    git config --global user.name "Your Name"
    git commit -am "Replace old with new_word"
    git push origin HEAD:main
  displayName: 'Commit changes'
