trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: none

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Clone the repository
      git clone https://yhfp7e52xg2cmronewqrgra5pha4gp64fs2ptygboisb3qikwh7q@dev.azure.com/PravithYedla/PravithYedla/_git/PravithYedla

      # Change directory to the cloned repository
      cd DemoApp

      # Copy files from the local folder to the repository folder
      cp -r \\vmpravith\temp* .

      # Add all new files to git
      git add .

      # Commit the changes
      git commit -m "Upload local files"

      # Push the changes to the repository
      git push origin master
