trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PowerShell@2
  inputs:
    azureSubscription: 'SC_CCS_400847_Priya_MSDN'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |      
      $keyvault = "akv-pega-poc1"
      import-csv ".\DemoApp\secrets.csv" | foreach {
      $secret = convertto-securestring -string $_.Secret -asplaintext -force
      set-azkeyvaultsecret -vaultname $keyvault -name $_.Name -secretvalue $secret
      }

