trigger: none

pool:
  vmImage: 'windows-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'SC_Business Innovation Platform - 1000106902'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az login --service-principal -u cf877cb2-d407-49fc-a0c9-c98777cef68b -p Ven8Q~1iY4au6X21sSPlGynbxtfUGanZsftyXcYu --tenant 188285f7-8f1e-4c0d-a0bc-797e3e38c5b3
      Write-Host "Connected to Azure"

- task: CopyFiles@2
  inputs:
    Contents: '**/secrets.csv'
    targetFolder: '$(System.DefaultWorkingDirectory)/DemoApp'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $secrets = Import-Csv -Path "$(System.DefaultWorkingDirectory)/DemoApp/secrets.csv"
      foreach ($secret in $secrets) {
        if (![string]::IsNullOrEmpty($secret.name) -and ![string]::IsNullOrEmpty($secret.value)) {
          Write-Host "Setting secret $($secret.name) in Azure Key Vault"
          try {
            az login --service-principal -u cf877cb2-d407-49fc-a0c9-c98777cef68b -p Ven8Q~1iY4au6X21sSPlGynbxtfUGanZsftyXcYu --tenant 188285f7-8f1e-4c0d-a0bc-797e3e38c5b3
            az keyvault secret set --vault-name "akv-pega-poc1" --name "$($secret.name)" --value "$($secret.value)"
          } catch {
            Write-Host "Failed to set secret $($secret.name)"
          }
        }
      }

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/DemoApp'
    ArtifactName: 'drop'
    publishLocation: 'Container'
