trigger:
- none

pool:
  vmImage: 'windows-latest'

steps:
- task: HelmInstaller@1
  inputs:
    helmVersionToInstall: 'latest'

- checkout: self
  persistCredentials: true

- task: Kubernetes@1
  displayName: 'kubectl login'
  inputs:
    connectionType: 'SC_CCS_400847_Priya_MSDN'
    kubernetesServiceEndpoint: 'akspegapoc2'
    command: 'login'

- powershell: |
    $csv = Import-Csv -Path ./DemoApp/sample.csv
    foreach ($row in $csv) {
        $deploymentPath = $row.name1
        $namespace = $row.name2
        kubectl apply -f ./my-app-4/$deploymentPath.yaml -n $namespace
    }
  displayName: 'helm deploy'

