trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CopyFiles@2
  displayName: 'Copy CSV file to $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/DemoApp'
    Contents: 'secrets.csv'
    TargetFolder: '$(System.DefaultWorkingDirectory)/DemoApp'

- task: AzureKeyVault@2
  displayName: 'Add secrets to Azure Key Vault'
  inputs:
    azureSubscription: 'SC_CCS_400847_Priya_MSDN'
    KeyVaultName: 'akv-pega-poc1'
    SecretsFilter: '$(System.DefaultWorkingDirectory)/DemoApp/secrets.csv'
    SecretsType: 'AzureKeyVault'