trigger:
- none

pool:
  vmImage: 'windows-latest'

variables:
- name: envTemplateFileTest
  ${{ if eq( variables['DevConnection'], 'Environ01' ) }}:
    value: ../Templates/DEV01-Variables-Template.yml
  ${{ if eq( variables['DevConnection'], 'Environ02' ) }}:
    value: ../Templates/DEV02-Variables-Template.yml

parameters:
- name: deploymentPath
  displayName: Deployment Path
  type: string
  default: './my-app-4/deployment.yaml'
  values:
  - './my-app-4/deployment.yaml'
  - './my-app-4/deployment-1.yaml'

steps:
- task: HelmInstaller@1
  inputs:
    helmVersionToInstall: 'latest'

- checkout: self
  persistCredentials: true

- task: Kubernetes@1
  displayName: 'kubectl login'
  inputs:
    connectionType: ${{ variables.connectionType }}
    kubernetesServiceEndpoint: ${{ variables.kubernetesServiceEndpoint }}
    command: 'login'

- script: |       
    kubectl apply -f ${{ parameters.deploymentPath }}
  displayName: 'helm deploy'
