trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $pat = "yhfp7e52xg2cmronewqrgra5pha4gp64fs2ptygboisb3qikwh7q"
      $url = "https://dev.azure.com/PravithYedla/_git/PravithYedla"
      $repo = "DemoApp"
      $folderPath = "C:\temp"
      $replaceWord = "azure-vote-back"
      $newWord = "newWord"

      # Upload all files in folder to repository
      Invoke-RestMethod -Uri "$url/$repo/_apis/git/repositories?api-version=6.0" `
        -Headers @{Authorization = "Bearer $pat"} `
        -Method Post `
        -ContentType "application/json" `
        -Body (ConvertTo-Json @{
          name = "$repo"
          project = @{
            id = "$(System.TeamProjectId)"
          }
        })

      git init
      git remote add origin "$url/$repo"
      git config --global user.email "you@example.com"
      git config --global user.name "Pravith Yedla"
      git add .
      git commit -m "Initial commit"
      git push -u origin main     
      