trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      
      $folderPath = $(System.DefaultWorkingDirectory)/DemoApp/*.yaml
      $replaceWord = "oldWord"
      $newWord = "newWord"


      # Replace word in all files
      Get-ChildItem -Path $folderPath -Recurse | ForEach-Object {
        (Get-Content $_.FullName) |
          ForEach-Object { $_ -replace $replaceWord, $newWord } |
          Set-Content $_.FullName
      }
