trigger: none

pool:
  vmImage: 'windows-latest'

steps:
- task: AzureCLI@2
  inputs:
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az login
      Write-Host "Connected to Azure"

- task: AzureKeyVault@2
  inputs:
    KeyVaultName: 'akv-pega-poc1'
    SecretsFilter: '*'
    RunAsPreJob: false

- task: CopyFiles@2
  inputs:
    Contents: '**/secrets.csv'
    targetFolder: '$(System.DefaultWorkingDirectory)/DemoApp'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $csv = Import-Csv -Path "$(System.DefaultWorkingDirectory)/DemoApp/secrets.csv"
      foreach ($row in $csv) {
        Write-Host "Setting secret $($row.name) in Azure Key Vault"
        az login
        az keyvault secret set --vault-name "akv-pega-poc1" --name "$($row.name)" --value "$($row.value)"
      }

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/DemoApp'
    ArtifactName: 'drop'
    publishLocation: 'Container'
