trigger:
- main
 
pool:
  vmImage: 'ubuntu-latest'
 
steps:
- task: KubernetesManifest@0
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: '<your-kubernetes-service-connection>'
    namespace: '<your-kubernetes-namespace>'
    manifests: |
      $(System.DefaultWorkingDirectory)/application/deployment.yaml