trigger:
- main
 
pool:
  vmImage: 'ubuntu-latest'
 
steps:
- task: KubernetesManifest@0
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: 'SC_Business Innovation Platform - 1000106902'
    namespace: 'demo-ns'
    manifests: |
      $(System.DefaultWorkingDirectory)/DemoApp/deployment.yaml
      