trigger:
- main
 
pool:
  vmImage: 'ubuntu-latest'
 
steps:
- task: KubernetesManifest@0
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: 'AKS'
    namespace: 'aks1'
    manifests: |
      $(System.DefaultWorkingDirectory)/DemoApp/deployment.yaml
      namespaceOverride: 'aks-pod'
      