trigger:
- none

pool:
  vmImage: ubuntu-latest

  variables:
  - group: akv-secrets

steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'SC_Business Innovation Platform - 1000106902'
    KeyVaultName: 'akv-pega-poc1'
    SecretsFilter: '*'
    RunAsPreJob: false

- task: CmdLine@2
  inputs:
    script: './DemoApp/secrets.csv'

- task: CopyFiles@2
  inputs:
    Contents: secrets.csv
    targetFolder: '$(System.DefaultWorkingDirectory)/DemoApp'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/DemoApp'
    ArtifactName: 'drop'
    publishLocation: 'Container'