jobs:
- job: UploadFiles
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: AzureFileCopy@4
    inputs:
      SourcePath: 'C:\temp'
      Destination: 'VSTSAgent'
      azureSubscription: 'SC_CCS_400847_Priya_MSDN'
  - task: PublishPipelineArtifact@1
    inputs:
      artifactName: 'my-artifact'
      targetPath: '$(System.DefaultWorkingDirectory)/DemoApp'
  - task: DownloadPipelineArtifact@2
    inputs:
      artifactName: 'my-artifact'
      targetPath: '$(System.DefaultWorkingDirectory)'
  - script: |
      git config --global user.email "you@example.com"
      git config --global user.name "Your Name"
      git add .
      git commit -m "Upload files"
      git push origin master
