parameters:
- name: folderPath
  type: string
  default: './DemoApp2'
- name: prefix
  type: string
  default: 'prefix_'
- name: deploymentDirectory
  type: string
  default: './DemoApp1'

trigger:
- none

pool:
  vmImage: 'windows-latest'

steps:
- task: HelmInstaller@1
  inputs:
    helmVersionToInstall: 'latest'

- checkout: self
  persistCredentials: true

- task: Kubernetes@1
  displayName: 'kubectl login'
  inputs:
    connectionType: 'SC_CCS_400847_Priya_MSDN'
    kubernetesServiceEndpoint: 'akspegapoc2'
    command: 'login'

- powershell: |
    $folderPath = "$(folderPath)"  # specify your folder path here
    $files = Get-ChildItem -Path $folderPath -File
    foreach ($file in $files) {
        $name = $file.BaseName
        $namespace = $name -replace '.cer$', ''  # replace '.cer' at the end of the string
        $deploymentPath = "$(prefix)" + ($name -replace '.crt$', '' -replace '$', '')
        kubectl apply -f "$(deploymentDirectory)"/$deploymentPath.yaml -n $namespace
    }
  displayName: 'helm deploy'
