trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az login
      echo "Connected to Azure"

- task: AzureKeyVault@2
  inputs:
    KeyVaultName: 'akv-pega-poc1'
    SecretsFilter: '*'
    RunAsPreJob: false

- task: CopyFiles@2
  inputs:
    Contents: '**/secrets.csv'
    targetFolder: '$(System.DefaultWorkingDirectory)/DemoApp'

- task: CmdLine@2
  inputs:
    script: |
      #!/bin/bash
      IFS=',' 
      while read -r name value
      do
        echo "Setting secret $name in Azure Key Vault"
        az login
        az keyvault secret set --vault-name "akv-pega-poc1" --name "$name" --value "$value"
      done < $(System.DefaultWorkingDirectory)/DemoApp/secrets.csv

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/DemoApp'
    ArtifactName: 'drop'
    publishLocation: 'Container'
