trigger:
- none

pool:
  name: Azure Pipelines
  vmImage: 'windows-latest'

stages:
- stage: dev
  displayName: functionapp
  dependsOn: []
  variables:
  - group: vg_backend_storage
  - group: vg_functionapp
  - name: stateFileName
    value: functionapp.tfstate

  jobs:
  - job: Terraform_Install
    displayName: Install Terraform
    steps:
    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest'

  - job: Terraform_Init_Upgrade
    displayName: Terraform Init Upgrade
    dependsOn: Terraform_Install
    steps:
    - task: AzureCLI@2
      displayName: 'Terraform Init - Upgrade'
      inputs:
        azureSubscription: 'SC_CCS_400847_Priya_MSDN'
        scriptType: 'pwsh'
        scriptLocation: 'inlineScript'
        inlineScript: |
          terraform init -upgrade
        workingDirectory: '$(System.DefaultWorkingDirectory)'

  - job: Terraform_Plan
    displayName: Build the Plan
    dependsOn: Terraform_Init_Upgrade
    steps:
    - template: ..\..\Templates\ExeSimpleTFPlan.yaml
      parameters:
        serviceConnection: 'SC_CCS_400847_Priya_MSDN'
        backendServiceConnection: 'SC_CCS_400847_Priya_MSDN'

  - job: WaitForValidation
    dependsOn: Terraform_Plan
    displayName: Wait for Plan Validation
    pool: server
    timeoutInMinutes: 4320
    steps:
    - task: ManualValidation@0
      timeoutInMinutes: 1440
      inputs:
        notifyUsers: |
          pravith.yedla@cognizant.com
        instructions: 'Please validate the plan and Resume to continue'
        onTimeout: 'reject'

  - job: Terraform_Apply
    dependsOn: WaitForValidation
    displayName: Build Resources As per Plan
    steps:
    - template: ..\..\Templates\ExeSimpleTFApply.yaml
      parameters:
        serviceConnection: 'SC_CCS_400847_Priya_MSDN'
        backendServiceConnection: 'SC_CCS_400847_Priya_MSDN'