trigger:
- none
 
pool:
  name: Azure Pipelines
  vmImage: 'windows-latest'

stages:
- stage: dev
  displayName: Resourcegroup
  dependsOn: []
  variables:
  - group: vg_backend_storage
  - group: vg_Resourcegroup
  - name: stateFileName
    value: Resourcegroup.tfstate 

  jobs:
  - job: Terraform_Plan
    displayName: Build the Plan
    steps:
    - template: ..\..\Templates\ExeSimpleTFPlan.yaml
      parameters:
        serviceConnection: 'SC_CCS_400847_Priya_MSDN'
        backendServiceConnection: 'SC_CCS_400847_Priya_MSDN'

  


