trigger:
- none

pool:
  name: Azure Pipelines
  vmImage: 'windows-latest'

jobs:
- task: AzureCLI@2
  displayName: 'Download Terraform'
  inputs:
    azureSubscription: 'your-service-connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      wget https://releases.hashicorp.com/terraform/1.3.7/terraform_1.3.7_linux_amd64.zip
      unzip terraform_1.3.7_linux_amd64.zip
      sudo mv terraform /usr/local/bin/
      terraform --version