trigger:
- none

pool:
  name: Azure Pipelines
  vmImage: 'windows-latest'

jobs:
- job: Terraform_Provider_Upgrade
  displayName: Upgrade Terraform Providers
  steps:
  - task: TerraformTaskV4@4
    displayName: 'Terraform Init - Upgrade'
    inputs:
      provider: 'azurerm'
      command: 'init'
      commandOptions: '-upgrade'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      terraformVersion: '1.4.6' # Or a specific version you need
      environmentServiceName: 'SC_CCS_400847_Priya_MSDN' # Using your service connection
      backendServiceArm: 'SC_CCS_400847_Priya_MSDN' # Using your service connection