trigger:
- none

pool:
  name: Azure Pipelines
  vmImage: 'windows-latest'

jobs:
- job: Terraform_Download_Test
  displayName: Terraform Download and Test
  steps:
  - task: AzureCLI@2
    displayName: 'Download Terraform and Test'
    inputs:
      azureSubscription: 'my-real-azure-service-connection' # Replace with your actual service connection name
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        $terraformVersion = "1.4.6"
        $terraformZip = "terraform_${terraformVersion}_windows_amd64.zip"
        $terraformUrl = "https://releases.hashicorp.com/terraform/${terraformVersion}/${terraformZip}"
        Write-Host "Downloading Terraform from: $terraformUrl"
        try {
          Invoke-WebRequest -Uri $terraformUrl -OutFile $terraformZip -ErrorAction Stop
          Write-Host "Download successful."
          Expand-Archive -Path $terraformZip -DestinationPath . -Force
          Rename-Item -Path "terraform_${terraformVersion}_windows_amd64" -NewName terraform -Force
          .\terraform\terraform.exe --version
        } catch {
          Write-Error "Failed to download or extract Terraform: $_"
          exit 1 # Exit with an error code
        }