jobs:
  - job: terraform_destroy
    steps:
      - task: TerraformInstaller@1
        displayName: "install"
        inputs:
          terraformVersion: "latest"
      - task: TerraformTaskV4@4
        displayName: "init"
        inputs:
          provider: "azurerm"
          command: "init"
          backendServiceArm: "${{ parameters.backendServiceArm }}"
          backendAzureRmSubscriptionId: "${{ parameters.backendAzureRmSubscriptionId }}"
          backendAzureRmResourceGroupName: "${{ parameters.backendAzureRmResourceGroupName }}"
          backendAzureRmStorageAccountName: "${{ parameters.backendAzureRmStorageAccountName }}"
          backendAzureRmContainerName: "${{ parameters.backendAzureRmContainerName }}"
          backendAzureRmKey: "${{ parameters.backendAzureRmKey }}"
          workingDirectory: "$(System.DefaultWorkingDirectory)/${{ parameters.rootFolder }}"
      - task: TerraformTaskV4@4
        displayName: "destroy"
        inputs:
          provider: "azurerm"
          command: "destroy"
          #commandOptions: '-input=false -auto-approve -var-file="$(System.DefaultWorkingDirectory)/${{ parameters.rootFolder }}/${{ parameters.tfvars }}"'
          environmentServiceNameAzureRM: "${{ parameters.backendServiceArm }}"
          workingDirectory: "$(System.DefaultWorkingDirectory)/${{ parameters.rootFolder }}"
