existing_resource_group_name  = "optum-chinmayee"
existing_virtual_network_name = "chinmayeevnet"
existing_subnet_name          = "chinmayeesubnet"
location                      = "East US"
existing_nsg                  = "chinmayee-nsg"
workspace_name                = "avd-workspace"
host_pool_name                = "avd-hostpool"
host_pool_type                = "Pooled"
load_balancer_type            = "BreadthFirst"
max_session_hosts             = 3
application_group_name        = "avd-desktop-application-group-name"
session_host_vm_name          = "avd-sessionhost"
vm_count                      = 3
vm_size                       = "Standard_D2a_v4"
vm_image_publisher            = "MicrosoftWindowsDesktop"
vm_image_offer                = "windows-11"
vm_image_sku                  = "win11-22h2-avd"
vm_image_version              = "latest"
os_disk_caching               = "ReadWrite"
os_disk_storage_account_type  = "StandardSSD_LRS"
os_disk_size_gb               = 32
admin_username                = "Avd-optum-admin"

