existing_resource_group_name  = "optum-chinmayee"
existing_virtual_network_name = "chinmayeevnet"
existing_subnet_name          = "chinmayeesubnet"
location                      = "East US"
existing_nsg                  = "chinmayee-nsg"
workspace_name                = "avd-workspace"
host_pool_name                = "avd-hostpool"
host_pool_type                = "Pooled"
load_balancer_type            = "BreadthFirst"
max_session_hosts             = 3
application_group_name        = "avd-desktop-application-group-name"
session_host_vm_name          = "avd-sessionhost"
vm_size                       = "Standard_D2a_v4"
admin_username                = "Avd-optum-admin"

