name: Terraform Azure Pipeline

on:
  workflow_dispatch:
    inputs:
      tf_plan:
        description: 'Run terraform plan'
        required: false
        default: 'false'
      tf_apply:
        description: 'Run terraform apply'
        required: false
        default: 'false'
      tf_destroy:
        description: 'Run terraform destroy'
        required: false
        default: 'false'

jobs:
  validate:
    name: Terraform Validate
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: iac
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

  plan:
    name: Terraform Plan
    needs: validate
    if: ${{ github.event.inputs.tf_plan == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: iac
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"

  apply:
    name: Terraform Apply
    needs: plan
    if: ${{ github.event.inputs.tf_apply == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: iac
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="terraform.tfvars"

  destroy:
    name: Terraform Destroy
    if: ${{ github.event.inputs.tf_destroy == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: iac
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var-file="terraform.tfvars"
