name: Terraform Validate

on:
  workflow_call:
    inputs:
      rootFolder:
        required: true
        type: string
      tfvars:
        required: false
        type: string

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.rootFolder }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate
