name: Deploy azure DNS Resolver
 
on: [workflow_dispatch]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
 
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURECRED }}
          enable-AzPSSession: true
          environment: AzureCloud  # or AzureChinaCloud, AzureUSGovernment, etc
 
      - name: Deploy Bicep file
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          template: infra-as-code/PrivateDNSResolver.bicep
          deploymentName: create_DNSResolver
#          parameters: adminPassword=${{ secrets.VMADMINPASSWORD }}
