name: Deploy Terraform Infrastructure

on:
  workflow_dispatch:
    inputs:
      rootFolder:
        description: 'Path to Terraform root directory'
        required: true
        default: './optum-network/project'
      tfvars:
        description: 'Path to .tfvars file'
        required: true
        default: 'parameters/dev-terrafrom.tfvars'
      action:
        description: 'Terraform action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - validate
          - apply
          - destroy
